import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "@/styles/globals.css";
import App from "next/app";
import AppContextProvider from "@/lib/AppContext";

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['200', '400', '500', '600', '700']
}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body className={`${lexendDeca.className} dark:bg-[#121215] bg-slate-100 text-[#84849d]`}>
          {children}
        </body>
      </html>
    </AppContextProvider>
  );
}
